### ISSUE TITLE
Mitigations for the ever-growing amount of data going into the datastore

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#105]
It's a fair way off becoming critical, but the amount of data in the 360Giving ecosystem is expected to continue to grow indefinitely: more publishers, more historic data, more augmentations to make the data more useful. 

At the moment, as I understand it, we basically start fresh each day: download data.json from the registry, iterate over it, download all of the data, perform our augmentations, store it in the database. I believe we have some in-database efficiencies, but nothing before then. 

It would be useful to understand the possible options for addressing this, their relative cost/complexity/etc, and we can decide on whether or not to do them in due course. 

Some initial ideas that came to mind:
* Adding a field into Salesforce that allows 360 staff to set how often a particular file is likely to be updated, and getting the datagetter to use a cached version of that data for a relevant period of time. We use our ability to get the file to do uptime monitoring, but that could be separated out. 
* Hash the files after download, and use cached results for any that haven't changed 
* Parallelise the download process (potentially even across multiple servers) to speed up the process of getting the files

@michaelwood @odscjames are likely to have more, and better, ideas!

**Comment by michaelwood** [comment]
Related: https://github.com/ThreeSixtyGiving/datagetter/issues/31

Some investigation would be needed to know if those headers on the file that could be accessed through a `HEAD` request are reliable, from what I understand browser cache routinely use this and fall back to a full fetch if needed.

Just a FYI we do (as of a few weeks ago) now run the download and flatten process in fully parallel separate processes. This has sped things up a lot but the database operations do still take a while.

**Comment by drkane** [comment]
Saw this the other day and wondered if it could help with the issue described above - moving validation against json schema to the database itself: https://github.com/supabase/pg_jsonschema

**Comment by michaelwood** [comment]
> Saw this the other day and wondered if it could help with the issue described above - moving validation against json schema to the database itself: https://github.com/supabase/pg_jsonschema

Interesting project to know about thanks. In the data pipeline context the validate step is required in/part of unflattening the data. If we had only json based publishers this could be perfect though.

**Comment by mariongalley** [comment]
This optimisation has been done in the datagetter project
