### ISSUE TITLE
Lookups for country and region codes in Datastore

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/datastore#113]
I have been investigating the current behaviour of Datastore additional data location lookups, for grants with beneficiary location provided with codes for English regions or England, Scotland, Northern Ireland or Wales codes. 

It looks like although the values provided in published data are shown in the **additional_data: locationLookup: areacode**, **name** and **type** fields

They are also referenced in **additional_data: locationLookup: source** and the associated fields.

However no data is being shown in the following fields, which suggests that the data is not being fully integrated into the geodata lookups.

- additional_data: locationLookup: ctrycd
- additional_data: locationLookup: ctrynm
- additional_data: locationLookup: rgncd
- additional_data: locationLookup: rgnnm

When the beneficiary locations UK-wide **K04000001**, the values provided in **additional_data: locationLookup: areacode** and **additional_data: locationLookup: source** revert to using either published recipient location data provided or falls back to recipient postcode derived from the org ID.

A file with example grants is available via [Planio issue 33069](https://opendataservices.plan.io/issues/33069)

It looks like there are two things that need to be resolved.

1. Getting the region and country codes to populate the ctry and rgn fields in the addtional data lookups, when beneficiary location region or country codes have been provided.
2. Adding UK country code to the lookup values, and then getting this to also to populate the ctry fields as appropriate.

This is linked to development previously done to add region lookups to the datastore, in closed ticket #71

**Comment by drkane** [comment]
I've now added a new file at <https://github.com/drkane/geo-lookups/blob/master/area_all_codes.csv> that includes all the codes for local authorities (lower and upper tier), combined authorities, regions & countries, in a format that is easier to import into the datastore consistently.

This should hopefully fix the issue below by ensuring that anything with the region code has that code in `rgncd` - at the moment that is blank.

**Comment by michaelwood** [comment]
This is part of the work is now deployed and a "load_geolookups" has been run on the datastore. Changes will appear in the datastore when the next datarun happens.

**Comment by michaelwood** [comment]
Think this can now be closed.
