### ISSUE TITLE
Develop a Google Colab notebook to ease access to the 360Giving data store

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#15]
The objective is to create the skeleton, so that further development and refinement can happen in our normal processes

It should
- Support CSV export, with features to support Google BQ import
- Demonstrate form-based interaction with the database
- Contain sample queries that users can adapt 
- Contain examples of using pandas to create aggregates
- Contain inline documentation
- Contain sample queries for the 'latest' data

**Comment by Bjwebb** [comment]
>    Support CSV export, with features to support Google BQ import

Do we have some existing code that generates a CSV suitable for BQ?

**Comment by robredpath** [comment]
> Do we have some existing code that generates a CSV suitable for BQ?

See https://opendataservices.plan.io/projects/three-sixty-giving/wiki/Loading_data_into_deployed_GrantNav/17 for how we used to load BQ. I think it's ok for us to do a minimal set of fields right now to ease complexity for this stage.

**Comment by Bjwebb** [comment]
Here's my finished Colab notebook for review: https://colab.research.google.com/drive/16s3wk4x1vo9yw1UDQwtDouf3UUnJgohR

**Comment by Bjwebb** [comment]
Something we do in the Kingfisher notebook, but don't have here yet, is a JSON download.

**Comment by michaelwood** [comment]
> Here's my finished Colab notebook for review: https://colab.research.google.com/drive/16s3wk4x1vo9yw1UDQwtDouf3UUnJgohR

Updated to new datastore hostname
