### ISSUE TITLE
Make augmented data on grants a separate object/col in the db

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/datastore#20]

**Comment by michaelwood** [comment]
I have implemented this in a dev branch. 

Unfortunately it does get pretty awkward because if we want to de-duplicate the effort of adding additional data - currently on import to the datastore and on import to grantnav  _and_ have the additional data in a separate object/column we will need to break compatibility with grantnav. 

Options:

1) Do a refactoring of gratnav's use of additional data so that the datastore's output is easily compatible with what grantnav is expecting. This is a fairly large job involving refactoring around 74 references to additional fields.

2) Write a system that flattens the data again on export from the datastore - however iterating through each grant object and manipulating it is quite costly.

3) Use the existing JSON `data` field on Grants to add the additional object and then modify grantnav's import function so that it re-maps the additional fields and therefore flattens the data, this would be fairly cheap as we're going through the data anyway, however it would mean that a query for `recipientDistrictName` would be `Grant->Data->additional_data->recipientDistrictName` rather than `Grant->additional_data->recipeintDistrictName`.

or something else I haven't thought of..

**Comment by drkane** [comment]
I think 2 makes the most sense - would it involve making changes to [datastore/api/grantnav/api.py#L24](https://github.com/ThreeSixtyGiving/datastore/blob/dev/datastore/api/grantnav/api.py#L24) to add in the additional data? - so it might become something like:

```python
{
    **grant.data,
    'recipientDistrictName': grant.additional_data['geo']['recipientDistrictName'],
    'recipientDistrictCode': grant.additional_data['geo']['recipientDistrictCode'],
    ...etc...
}
```

That would give us the opportunity of refactoring the additional_data field to improve the way the data is imported - eg over the medium term I'd like to expand the range of geographic information that's captured, also include beneficiary location, and also expand the range of charity/organisation data that is included (I think there are potential links with find-that-charity here too).

**Comment by michaelwood** [comment]
Unfortunately that bit of code referenced is a bit of a red-herring as that was an experimental bit of API which we ended up not using. (I've not removed it to avoid confusion) . The code that handles the export is here: https://github.com/ThreeSixtyGiving/datastore/blob/dev/datastore/db/management/commands/create_datagetter_data.py#L54

**Comment by michaelwood** [comment]
And for reference this commit/branch has the WIP for the additional data https://github.com/ThreeSixtyGiving/datastore/commit/946a85ee685bb01deec0d927801dd1f17e20d568 the only part I'm missing in that commit is adapting the export into grantnav as per options

**Comment by drkane** [comment]
Ah okay - that makes sense, and does look more tricky to integrate. Might be something for an SQL view or similar? 

In the 946a85e commit, in [this function](https://github.com/ThreeSixtyGiving/datastore/blob/mw/dev-additional-data/datastore/additional_data/grant/__init__.py#L132-L146) doesn't it need to create separate records for the id_and_name field for both funder and recipient? It looks like it would just create one id_and_name record?

**Comment by michaelwood** [comment]
> In the [946a85e](https://github.com/ThreeSixtyGiving/datastore/commit/946a85ee685bb01deec0d927801dd1f17e20d568) commit, in [this function](https://github.com/ThreeSixtyGiving/datastore/blob/mw/dev-additional-data/datastore/additional_data/grant/__init__.py#L132-L146) doesn't it need to create separate records for the `id_and_name` field for both funder and recipient? It looks like it would just create one `id_and_name` record attached to the grant?

That one is a bit of a strange one, I'm not sure of the history but I believe this is used to generate the arrow display on a grant in grantnav. 

For example https://grantnav.threesixtygiving.org/grant/360G-SE-2011011413LOTT :
```
Funding Organization
Sport England (GB-COH-RC000766)

£1,600
->
13 Dec 2011

Recipient Organization
Lilian Baylis Technology School (GB-COH-09000742)
```
It might make sense to leave that only on the grantnav import side, if there are going to be such things. I think I'm in favour of the idea that we do a flatten on import to grantnav, that seems to put us in the right future direction. Side note - I wonder if the schema should have formal provision for additional data fields.

My postgresql foo isn't hugely strong but I'm not sure that you can easily create a view that combines two JSON fields without having to specify every field name and construct a view based on either creating a new json field or multiple columns. Specifying the fields would mean the view would have to be kept in sync with the fields in the two JSON fields. Not impossible but quite finickity. I will check my thinking with the others devs on this.

**Comment by drkane** [comment]
According to my [in depth research](https://stackoverflow.com/a/44038002) it's possible to use `||` to join two jsonb fields - so `data || additional_data` should work.
