### ISSUE TITLE
Expanding the geographical field

### ISSUE THREAD

**Issue by BibianaC** [ThreeSixtyGiving/datastore#27]
For recipient location based on postcode, expanding the geographical fields collected to include all of those included in the [NSPL](https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=all(PRD_NSPL%2CFEB_2020))

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Datastore - Expanding the geographical field](https://trello.com/c/KcIyyu6Z/59-datastore-expanding-the-geographical-field)

**Comment by robredpath** [comment]
```
➜  Data pwd
/Users/robredpath/Downloads/NSPL_FEB_2020_UK/Data
➜  Data head -1 NSPL_FEB_2020_UK.csv
pcd,pcd2,pcds,dointr,doterm,usertype,oseast1m,osnrth1m,osgrdind,oa11,cty,ced,laua,ward,hlthau,nhser,ctry,rgn,pcon,eer,teclec,ttwa,pct,nuts,park,lsoa11,msoa11,wz11,ccg,bua11,buasd11,ru11ind,oac11,lat,long,lep1,lep2,pfa,imd,calncv,stp
```

**Comment by robredpath** [comment]
```
➜  Documents pwd
/Users/robredpath/Downloads/NSPL_FEB_2020_UK/Documents
➜  Documents head -2 "PFA names and codes GB as at 12_15.csv"
PFA15CD,PFA15NM
E23000001,Metropolitan Police
```

**Comment by robredpath** [comment]
So the main file is all codes, but there's lookup files that are pretty comprehensive

**Comment by robredpath** [comment]
I can't remember right now if we put the codes into the data or whether we pull in the human-readable descriptions. Or both. Or what we want to do. We can look into that at the start of the work, and @drkane might have views on what's most useful!

We must do *some* human-readable lookups because this is the data that powers the facets in GrantNav, IIRC, but not necessarily all.

**Comment by robredpath** [comment]
From @drkane "keep it in codes for as long as possible until you need to display it to the user....but users who want CSVs will probably want names"

**Comment by michaelwood** [comment]
We will investigate having the postcode lookup data in the database table which the datastore will manage and query.

**Comment by drkane** [comment]
Here's the script from findthatpostcode that imports the NSPL: https://github.com/drkane/find-that-postcode/blob/master/findthatpostcode/commands/postcodes.py

And this gets a list of the names for each of the codes from the "Code History database": https://github.com/drkane/find-that-postcode/blob/master/findthatpostcode/commands/codes.py#L111-L193

NB One issues with these is that they don't have a persistent URL, but they only change every few months anyway.
