### ISSUE TITLE
Query request: identify cases where the same grant ID exists in two files

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#3]
See https://opendataservices.plan.io/issues/16817 - this was something that was requested for GN but might be easier here. 

Not a priority for our current work but logging this here.

**Comment by KDuerden** [comment]
thanks @robredpath - this issue still does crop up from time to time.

**Comment by drkane** [comment]
Thanks to the magic of the datastore, there's now a colab notebook which does exactly this: https://colab.research.google.com/drive/1B_md5gkQZJtG4DcHS39_O439EfDArV1l?authuser=1

**Comment by robredpath** [comment]
@drkane cool! Could you share it with me? I'd be interested to see it!

**Comment by drkane** [comment]
@robredpath should now be shared with you and @michaelwood
