### ISSUE TITLE
Refactor of additional_data module

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/datastore#31]
I'm intending on slightly refactoring the additional_data module so that it makes a bit more sense now that the grantnav additional data isn't the only one.

additional_data
├── admin.py
├── apps.py
├── grant  **RENAME**  sources
│   ├─── **NEW** findthatcharity.py #28 
│   ├── **NEW** nspl.py #27 
│   ├── **NEW** otherthing.py #29
│   ├── charity_names.json
│   ├── codelist.csv
│   ├── codepoint_with_heading.csv.gz
│   ├── fetch_charity_data.py
│   ├── __init__.py **MOVE UP LEVEL RENAME TO factory (or similar) this is where the data will be added to the stored object additional_data** 
│   ├── primary_funding_org_name.json
│   └── WD15_LGD15_NI_LU.csv
├── __init__.py
├── management
│   ├── commands
│   │   ├── load_nspl.py
├── migrations
│   ├── 0001_initial.py
│   ├── __init__.py
├── models.py

@drkane @BibianaC

**Comment by michaelwood** [comment]
Should have added - I'm intending to do this unless anyone has objections/thoughts/better ideas!

**Comment by drkane** [comment]
Makes sense to me
