### ISSUE TITLE
List of additional fields is missing commas

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/datastore#42]
https://github.com/ThreeSixtyGiving/datastore/blob/ccb3ab82535ebdcce824c89b539b09f4ec170e7d/datastore/additional_data/sources/local_files.py#L15-L21

This will cause an issue with the grantnav update

**Comment by michaelwood** [comment]
This is there to make sure only those additional fields which grantnav is expecting are present. There's a bit more explanation in the commit message https://github.com/ThreeSixtyGiving/datastore/commit/2bce51d0262df8dee9f0fd78ca331630170b1a84 

What do you see as being the issue?

**Comment by michaelwood** [comment]
Sorry, yeah opps now I see it.
