### ISSUE TITLE
Contents of view_latest_grant

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/datastore#50]
There's a couple of things I've found that aren't in `view_latest_grant` that I think would be useful to include. 

- One is the `additional_data` field, particularly now that it's more detailed
- The other is the source information - particularly the publisher and licence, but potentially all of it. I think it would be good practice to enable users to include the source as easily as possible.

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make changes to view_latest_grant in the datastore](https://trello.com/c/yCozYa9m/85-make-changes-to-viewlatestgrant-in-the-datastore)

**Comment by michaelwood** [comment]
I've updated the view:

(I named db.sourcefile.data as source_data to avoid conflict with db.grant.data)

```sql
CREATE OR REPLACE VIEW public.view_latest_grant
AS SELECT db_grant.id,
    db_grant.grant_id,
    db_grant.data,
    db_grant.source_file_id,
    db_grant.getter_run_id,
    db_grant.publisher_id,
    db_grant.additional_data,
    db_sourcefile.data as source_data
   FROM db_grant
     JOIN db_sourcefile_latest ON db_grant.source_file_id = db_sourcefile_latest.sourcefile_id
     JOIN db_latest ON db_sourcefile_latest.latest_id = db_latest.id
     JOIN db_sourcefile on db_grant.source_file_id = db_sourcefile.id
  WHERE db_latest.series = 'CURRENT'::text;
```

**Comment by drkane** [comment]
works great - thanks!
