### ISSUE TITLE
Add funder org type field / metadata to the datastore

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/datastore#56]
This field does not exist today, but can be done with Find That Charity service. This will allow us to add relevant filters to GrantNav in the future. 
There are two type of org type field - 
1. Legal organisation type - central government, local government, trust and foundations, corporations - can be extract by find that charity. 
2. Type of philanthropic body - lottery funder, community foundation, private foundation, trust. More work need to be done here. @drkane - please add here as well.

**Comment by drkane** [comment]
Here's a previous attempt to do this automatically in SQL:

https://github.com/ThreeSixtyGiving/Insights/blob/2f501dad4bcd53de943bd9aad8fef9aa0396c297/tsg_insights/commands/dataimport.py#L475-L483

```
"fundingOrganization_type" = case
    when "fundingOrganization_id" in ('GB-COH-RC000766', '360G-blf', 'GB-CHC-1036733', 'GB-GOR-PC390') then 'National Lottery'
    when "fundingOrganization_id" ilike 'GB-GOR-%' then 'Government'
    when "fundingOrganization_id" ilike 'GB-LAE-%' then 'Local Authority'
    when "fundingOrganization_id" ilike 'GB-LAN-%' then 'Local Authority'
    when "fundingOrganization_id" ilike 'GB-LAS-%' then 'Local Authority'
    when "fundingOrganization_id" ilike 'GB-PLA-%' then 'Local Authority'
    when "fundingOrganization_name" ilike '%Community Foundation%' then 'Community Foundation'
    else 'Charitable Funder' end
```

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare data services for (pre-) release of government grants data](https://trello.com/c/uFYi553h/108-prepare-data-services-for-pre-release-of-government-grants-data)
