### ISSUE TITLE
Decide on terminology for what the 'right' data to be loading into GrantNav is

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#6]
We currently refer to data as 'canonical', but that implies an authoritative-ness that isn't true as we're effectively mirroring data. 

Thoughts @drkane @kindly @Bjwebb @michaelwood ?

**Comment by drkane** [comment]
My vote would be for 'latest' or 'latest valid'

**Comment by michaelwood** [comment]
Canonical has been replaced for 'Latest'.
