### ISSUE TITLE
Add region and country to geo lookups

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/datastore#71]
At the moment a geocode in recipient or beneficiary location is ignored if it's a country or a region. These should be added as `GeoLookup` objects so that they can be included in the data.

The example given was WCVA who publish grants with a geocode of `W92000004` - eg <https://grantnav.threesixtygiving.org/grant/360G-WCVA-27082>

The data would need to be added to https://github.com/ThreeSixtyGiving/datastore/blob/master/datastore/additional_data/sources/geo_lookup.py

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/ThreeSixtyGiving/datastore/issues/71](https://trello.com/c/lXUpK7SC/143-https-githubcom-threesixtygiving-datastore-issues-71)

**Comment by drkane** [comment]
Fixing this partly depends on these codes being available in https://github.com/drkane/geo-lookups/ (or similar format) - I've now updated this so there are files for region, country and combined authority. So it should just be a case of adding the files to https://github.com/ThreeSixtyGiving/datastore/blob/94cf54537c3b87f1c5ae7751c53585bc4c27d705/datastore/additional_data/sources/geo_lookup.py#L14-L50

**Comment by drkane** [comment]
I've now added equivalent files for [regions](https://github.com/drkane/geo-lookups/blob/master/rgn_all_codes.csv) and [countries](https://github.com/drkane/geo-lookups/blob/master/ctry_all_codes.csv) to the [geo-lookups](https://github.com/drkane/geo-lookups/) repository, so it should be straightforward to add these to the `SOURCE_URLS` dictionary.

We should also include the [Upper tier local authorities](https://github.com/drkane/geo-lookups/blob/master/utla_all_codes.csv) and [Combined Authority](https://github.com/drkane/geo-lookups/blob/master/cauth_all_codes.csv) files here too.

**Comment by michaelwood** [comment]
> I've now added equivalent files for [regions](https://github.com/drkane/geo-lookups/blob/master/rgn_all_codes.csv) and [countries](https://github.com/drkane/geo-lookups/blob/master/ctry_all_codes.csv) to the [geo-lookups](https://github.com/drkane/geo-lookups/) repository, so it should be straightforward to add these to the `SOURCE_URLS` dictionary.
> 
> We should also include the [Upper tier local authorities](https://github.com/drkane/geo-lookups/blob/master/utla_all_codes.csv) and [Combined Authority](https://github.com/drkane/geo-lookups/blob/master/cauth_all_codes.csv) files here too.

@drkane do you have preferences on what field names should be called? or should we just use `rgn` `ctry` `utla` and `cuath` ?

**Comment by drkane** [comment]
> should we just use `rgn` `ctry` `utla` and `cuath` ?

Those work for me!
