### ISSUE TITLE
Make extra tables - Funder etc - work!

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datastore#9]

**Comment by michaelwood** [comment]
Is this issue effectively to address #7 ?

**Comment by michaelwood** [comment]
http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/funders (download links )

**Comment by michaelwood** [comment]
Fix for this is now in the grantnav es7 pull request https://github.com/ThreeSixtyGiving/grantnav/pull/515/commits/beec741b8770953c549ed191958d6e5f5496b2fb
